// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function BackSplashFour({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/back-splash-four.glb');

//   // Optimized material with dynamic highlighting
//   const material = useMemo(() => {
//     const mat = materials['Plank wood'].clone();
//     if (isActive) {
//       // material.emissive.set('blue');;
//       mat.emissiveIntensity = 0.6;
//       mat.roughness = 0.4; // Slight polish effect
//     }
//     return mat;
//   }, [isActive, materials['Plank wood']]);

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube.geometry}
//         material={material}
//         position={[-0.792, 1.826, -1.064]}
//         rotation={[0, 0, 0.052]}
//         scale={[1.001, 1.167, 1]}
//       />
//     </group>
//   );
// }

// useGLTF.preload('./models/parts144/back-splash-four.glb');


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BackSplashFour(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/back-splash-four.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Plank wood']}
        position={[-0.792, 1.826, -1.064]}
        rotation={[0, 0, 0.052]}
        scale={[1.001, 1.167, 1]}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/back-splash-four.glb')
