// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function BackSplashOne({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/back-splash-one.glb');

//   const activeMaterial = useMemo(() => {
//     const mat = materials['Material.036'].clone();
//     if (isActive) {
//       // // material.emissive.set('blue');;
//       mat.emissiveIntensity = 0.5;
//       mat.envMapIntensity = 1.2;
//     }
//     return mat;
//   }, [isActive, materials['Material.036']]);

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube.geometry}
//         material={activeMaterial}
//         position={[-0.792, 1.826, -1.064]}
//         rotation={[0, 0, 0.052]}
//         scale={[1.001, 1.167, 1]}
//       />
//     </group>
//   );
// }

// useGLTF.preload('./models/parts144/back-splash-one.glb');

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BackSplashOne(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/back-splash-one.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.036']}
        position={[-0.792, 1.826, -1.064]}
        rotation={[0, 0, 0.052]}
        scale={[1.001, 1.167, 1]}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/back-splash-one.glb')
