// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function BackSplashTwo({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/back-splash-two.glb')

//   const material = useMemo(() => {
//     const mat = materials['[Tile Hexagon White]1.001'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.8
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube.geometry}
//         material={material}
//         position={[-0.792, 1.826, -1.064]}
//         rotation={[0, 0, 0.052]}
//         scale={[1.001, 1.167, 1]}
//       />
//     </group>
//   )
// }

// useGLTF.preload('./models/parts144/back-splash-two.glb')


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BackSplashTwo(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/back-splash-two.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['[Tile Hexagon White]1.001']}
        position={[-0.792, 1.826, -1.064]}
        rotation={[0, 0, 0.052]}
        scale={[1.001, 1.167, 1]}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/back-splash-two.glb')
