// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function Ceiling({ isSelected, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/Ceiling.glb');

//   // Create a new material instance to avoid modifying the original material
//   const highlightedMaterial = useMemo(() => {
//     const material = materials['Oak wood'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials]);

//   return (
//     <group {...props} dispose={null} >
//       <mesh

//         castShadow
//         receiveShadow
//         geometry={nodes.Cube122.geometry}
//         material={isSelected ? highlightedMaterial : materials['Oak wood']}
//         position={[-0.016, 2.524, -1.028]}
//       />
//     </group>
//   );
// }

// useGLTF.preload('./models/parts144/Ceiling.glb');

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Ceiling(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/ceiling.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube122.geometry}
        material={materials['Oak wood']}
        position={[-0.016, 2.524, -1.028]}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/ceiling.glb')
