// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function Control_Panel({ isSelected, ...props }) {
//   const { nodes, materials } = useGLTF('./models/Control_Panel.glb');

//   // Create a new material instance to avoid modifying the original material
//   const highlightedMaterial = useMemo(() => {
//     const material = materials.CP.clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials]);

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Control_Panel.geometry}
//         material={isSelected ? highlightedMaterial : materials.CP}
//         position={[0, 0, 0]}
//         rotation={[0, 0, 0]}
//         scale={0.01}
//       />
//     </group>
//   );
// }

// useGLTF.preload('./models/Control_Panel.glb');

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Control_Panel(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/Control_Panel.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Control_Panel.geometry}
        material={materials.CP}
        position={[0.279, 2.102, -0.641]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/Control_Panel.glb')
