// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function CounterTopFour({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/countertop-four.glb');

//   const marbleMaterial = useMemo(() => {
//     const mat = materials['Marble.002'].clone();
//     if (isActive) {
//       // material.emissive.set('blue');;
//       mat.emissiveIntensity = 0.7;
//     }
//     return mat;
//   }, [isActive, materials]);

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube038.geometry}
//         material={marbleMaterial}
//         position={[-0.559, 1.424, -0.491]}
//       />
//     </group>
//   );
// }

// useGLTF.preload('./models/parts144/countertop-four.glb');

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CounterTopFour(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/countertop-four.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038.geometry}
        material={materials['Marble.002']}
        position={[-0.559, 1.424, -0.491]}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/countertop-four.glb')
