// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function CounterTopFive({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/countertop-five.glb')

//   const whiteMarbleMat = useMemo(() => {
//     const mat = materials.white_marble.clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.8
//     }
//     return mat
//   }, [isActive, materials])

//   const material031 = useMemo(() => {
//     const mat = materials['Material.031'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.8
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <group position={[-0.559, 1.424, -0.491]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube015.geometry}
//           material={whiteMarbleMat}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube015_1.geometry}
//           material={material031}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('./models/parts144/countertop-five.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CounterTopFive(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/countertop-five.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.559, 1.424, -0.491]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={materials.white_marble}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_1.geometry}
          material={materials['Material.031']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/in-parts144/countertop-five.glb')