// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function CurtainOne({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/curtain-one.glb')

//   const sheerMaterial = useMemo(() => {
//     const mat = materials['sheer.002'].clone()
//     if (isActive) {
//       // mat.emissive.set('#ff9999') // Soft red for curtain fabric
//       mat.emissiveIntensity = 0.4
//       mat.transparent = true
//       mat.opacity = 0.8
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.SHEER002.geometry}
//         material={sheerMaterial}
//         position={[0.002, 1.38, 0.613]}
//         scale={[0.272, 0.386, 0.503]}
//       />
//     </group>
//   )
// }

// useGLTF.preload('./models/parts144/curtain-one.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export default function CurtainOne(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/curtain-one.glb')

  // Clone the material and set the color to light gray
  const curtainMaterial = materials['sheer.002'].clone()
  curtainMaterial.color = new THREE.Color('#d3d3d3') // light gray

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHEER002.geometry}
        material={curtainMaterial}
        position={[0.002, 1.38, 0.613]}
        scale={[0.272, 0.386, 0.503]}
      />
    </group>
  )
}


useGLTF.preload('./models/in-parts144/curtain-one.glb')
