// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function CurtainTwo({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/curtain-two.glb')

//   const fabricMat = useMemo(() => {
//     const mat = materials['Fabric Smooth Gray'].clone()
//     if (isActive) {
//       // mat.emissive.set('#ff9999') // Soft pink highlight
//       mat.emissiveIntensity = 0.3
//     }
//     return mat
//   }, [isActive, materials])

//   const material033 = useMemo(() => {
//     const mat = materials['Material.033'].clone()
//     if (isActive) {
//       // mat.emissive.set('#ff9999')
//       mat.emissiveIntensity = 0.3
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <group
//         position={[-0.006, 1.361, 0.757]}
//         rotation={[-Math.PI, 1.518, 0]}
//         scale={[-0.226, -0.576, -0.424]}
//       >
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane007.geometry}
//           material={fabricMat}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane007_1.geometry}
//           material={material033}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('./models/parts144/curtain-two.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CurtainTwo(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/curtain-two.glb')
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.006, 1.361, 0.757]}
        rotation={[-Math.PI, 1.518, 0]}
        scale={[-0.226, -0.576, -0.424]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007.geometry}
          material={materials['Fabric Smooth Gray']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_1.geometry}
          material={materials['Material.033']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/in-parts144/curtain-two.glb')