// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function CushionOne({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/cushion-one.glb')

//   const material053 = useMemo(() => {
//     const mat = materials['Material.053'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.6
//     }
//     return mat
//   }, [isActive, materials])

//   const estampaMat = useMemo(() => {
//     const mat = materials['Estampa-01.003'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.6
//     }
//     return mat
//   }, [isActive, materials])

//   const patternMat = useMemo(() => {
//     const mat = materials['Pattern cushion estampa-02.003'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.6
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <group position={[-0.016, 1.181, -1.961]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39005.geometry}
//           material={material053}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39005_1.geometry}
//           material={estampaMat}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39005_2.geometry}
//           material={patternMat}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('./models/parts144/cushion-one.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CushionOne(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/cushion-one.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.016, 1.181, -1.961]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39005.geometry}
          material={materials['Material.053']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39005_1.geometry}
          material={materials['Estampa-01.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39005_2.geometry}
          material={materials['Pattern cushion estampa-02.003']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/in-parts144/cushion-one.glb')
