// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function DinetteCushionSet({ isSelected, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/DinetteCushionSet.glb');

//   // Create highlighted materials for each unique material
//   const highlightedMaterialLa = useMemo(() => {
//     const material = materials.La.clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials.La]);

//   const highlightedMaterialEstampa01 = useMemo(() => {
//     const material = materials['Estampa-01'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Estampa-01']]);

//   const highlightedMaterialPatternCushion = useMemo(() => {
//     const material = materials['Pattern cushion estampa-02'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Pattern cushion estampa-02']]);

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.trunk_part_39009.geometry}
//         material={isSelected ? highlightedMaterialLa : materials.La}
//         position={[0.541, 1.094, -1.725]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.trunk_part_39023.geometry}
//         material={isSelected ? highlightedMaterialLa : materials.La}
//         position={[-0.824, 1.266, -1.849]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.trunk_part_39037.geometry}
//         material={isSelected ? highlightedMaterialLa : materials.La}
//         position={[-0.576, 1.101, -1.849]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.trunk_part_39040.geometry}
//         material={isSelected ? highlightedMaterialLa : materials.La}
//         position={[0.786, 1.266, -1.717]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes['Patterned_pillow-01'].geometry}
//         material={isSelected ? highlightedMaterialEstampa01 : materials['Estampa-01']}
//         position={[-0.547, 1.165, -1.572]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes['Patterned_pillow-01001'].geometry}
//         material={isSelected ? highlightedMaterialEstampa01 : materials['Estampa-01']}
//         position={[0.51, 1.165, -2.354]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes['Pattern_cushion-D'].geometry}
//         material={isSelected ? highlightedMaterialPatternCushion : materials['Pattern cushion estampa-02']}
//         position={[-0.763, 1.312, -2.252]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes['Pattern_cushion-D001'].geometry}
//         material={isSelected ? highlightedMaterialPatternCushion : materials['Pattern cushion estampa-02']}
//         position={[0.726, 1.312, -1.708]}
//       />
//     </group>
//   );
// }

// useGLTF.preload('./models/parts144/DinetteCushionSet.glb');

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function DinetteCushionSet(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/dinette-cushion-set.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk_part_39009.geometry}
        material={materials.La}
        position={[0.541, 1.094, -1.725]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk_part_39023.geometry}
        material={materials.La}
        position={[-0.824, 1.266, -1.849]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk_part_39037.geometry}
        material={materials.La}
        position={[-0.576, 1.101, -1.849]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk_part_39040.geometry}
        material={materials.La}
        position={[0.786, 1.266, -1.717]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Patterned_pillow-01'].geometry}
        material={materials['Estampa-01']}
        position={[-0.547, 1.165, -1.572]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Patterned_pillow-01001'].geometry}
        material={materials['Estampa-01']}
        position={[0.51, 1.165, -2.354]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Pattern_cushion-D'].geometry}
        material={materials['Pattern cushion estampa-02']}
        position={[-0.763, 1.312, -2.252]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Pattern_cushion-D001'].geometry}
        material={materials['Pattern cushion estampa-02']}
        position={[0.726, 1.312, -1.708]}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/dinette-cushion-set.glb')