// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function DoorPanelOne({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/door-pannel-one.glb')

//   const windowMaterial = useMemo(() => {
//     const mat = materials['window body.002'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.7
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.rear_door_l001.geometry}
//         material={windowMaterial}
//         position={[0.019, 1.52, -2.76]}
//       />
//     </group>
//   )
// }

// useGLTF.preload('./models/parts144/door-pannel-one.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function DoorPanelOne(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/door-pannel-one.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rear_door_l001.geometry}
        material={materials['window body.002']}
        position={[0.019, 1.52, -2.76]}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/door-pannel-one.glb')
