// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function DoorPanelTwo({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/door-pannel-two.glb')

//   const panelMaterial = useMemo(() => {
//     const mat = materials['Material.002'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.7
//     }
//     return mat
//   }, [isActive, materials])

//   const paintMaterial = useMemo(() => {
//     const mat = materials['carpaint.002'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.7
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <group position={[-0.005, 1.47, -2.751]} rotation={[Math.PI, -1.012, Math.PI]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube020.geometry}
//           material={panelMaterial}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube020_1.geometry}
//           material={paintMaterial}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('./models/parts144/door-pannel-two.glb')


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function DoorPanelTwo(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/door-pannel-two.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.005, 1.47, -2.751]} rotation={[Math.PI, -1.012, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials['carpaint.002']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/in-parts144/door-pannel-two.glb')