// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function Elevatorbed({ isSelected, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/Elevatorbed.glb');

//   // Create highlighted materials for each unique material
//   const highlightedMaterial003 = useMemo(() => {
//     const material = materials['Material.003'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Material.003']]);

//   const highlightedMaterial004 = useMemo(() => {
//     const material = materials['Material.004'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Material.004']]);

//   const highlightedMaterialBlanketFabric = useMemo(() => {
//     const material = materials['Blanket_fabric_5.001'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Blanket_fabric_5.001']]);

//   const highlightedMaterial034 = useMemo(() => {
//     const material = materials['Material.034'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Material.034']]);

//   return (
//     <group {...props} dispose={null}>
//       <group position={[0.002, 1.864, -1.942]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Document002_1.geometry}
//           material={isSelected ? highlightedMaterial003 : materials['Material.003']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Document002_2.geometry}
//           material={isSelected ? highlightedMaterial004 : materials['Material.004']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Document002_3.geometry}
//           material={isSelected ? highlightedMaterialBlanketFabric : materials['Blanket_fabric_5.001']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Document002_4.geometry}
//           material={isSelected ? highlightedMaterial034 : materials['Material.034']}
//         />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload('./models/parts144/Elevatorbed.glb');


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Elevatorbed(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/elevator-bed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.002, 1.864, -1.942]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Document002_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Document002_2.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Document002_3.geometry}
          material={materials['Blanket_fabric_5.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Document002_4.geometry}
          material={materials['Material.034']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/in-parts144/elevator-bed.glb')
