// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function Faucet({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('/models/parts144/faucet.glb')

//   const faucetMaterial = useMemo(() => {
//     const mat = materials['Black.001'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.8
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <mesh
//       {...props}
//       castShadow
//       receiveShadow
//       geometry={nodes.Cube014.geometry}
//       material={faucetMaterial}
//       position={[-0.693, 1.701, -0.432]}
//       dispose={null}
//     />
//   )
// }

// useGLTF.preload('/models/parts144/faucet.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Faucet(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/faucet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials['Black.001']}
        position={[-0.693, 1.701, -0.432]}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/faucet.glb')
