// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';
// import { MeshStandardMaterial } from 'three';

// export default function FlooringTwo({ isActive, ...props }) {
//   const { nodes } = useGLTF('/models/parts144/flooring-two.glb');

//   const customMaterial = useMemo(() => {
//     const mat = new MeshStandardMaterial();
//     if (isActive) {
//       // material.emissive.set('blue');;
//       mat.emissiveIntensity = 0.5;
//     }
//     // Custom material properties
//     mat.color.set('#8B4513'); // Brown wood color
//     mat.roughness = 0.7;
//     mat.metalness = 0.1;
//     return mat;
//   }, [isActive]);

//   return (
//     <mesh
//       {...props}
//       geometry={nodes.Van_body002.geometry}
//       material={customMaterial}
//       castShadow
//       receiveShadow
//       position={[0.001, 0.588, -1.006]}
//       dispose={null}

//     />
//   );
// }

// // useGLTF.preload('/models/parts144/flooring-two.glb');

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function FlooringTwo(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/flooring-two.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Van_body002.geometry}
        material={materials['Rough Oak Wood Veneer']}
        position={[0.001, 0.588, -1.006]}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/flooring-two.glb')