// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function FlooringFour({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/flooring-four.glb')

//   const floorMaterial = useMemo(() => {
//     const mat = materials['Material.035'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.5
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Van_body002.geometry}
//         material={floorMaterial}
//         position={[0.001, 0.588, -1.006]}
//       />
//     </group>
//   )
// }

// useGLTF.preload('./models/parts144/flooring-four.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function FlooringFour(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/flooring-four.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Van_body002.geometry}
        material={materials['Material.035']}
        position={[0.001, 0.588, -1.006]}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/flooring-four.glb')
