// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function FlooringOne({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('/models/parts144/flooring-one.glb');

//   const woodMaterial = useMemo(() => {
//     const mat = materials['Wood.001'].clone();
//     if (isActive) {
//       // material.emissive.set('blue');;
//       mat.emissiveIntensity = 0.5;
//     }
//     return mat;
//   }, [isActive, materials]);

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Van_body002.geometry}
//         material={woodMaterial}
//         position={[0.001, 0.588, -1.006]}
//       />
//     </group>
//   );
// }

// useGLTF.preload('/models/parts144/flooring-one.glb');

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function FlooringOne(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/flooring-one.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Van_body002.geometry}
        material={materials['Wood.001']}
        position={[0.001, 0.588, -1.006]}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/flooring-one.glb')
