// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function KitchenCabinet({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('/models/parts144/kitchen-cabinet.glb');

//   const blackMaterial = useMemo(() => {
//     const mat = materials.Black.clone();
//     if (isActive) {
//       // material.emissive.set('blue');;
//       mat.emissiveIntensity = 0.8;
//     }
//     return mat;
//   }, [isActive, materials]);

//   const latchesMaterial = useMemo(() => {
//     const mat = materials.latches.clone();
//     if (isActive) {
//       // material.emissive.set('blue');;
//       mat.emissiveIntensity = 0.8;
//     }
//     return mat;
//   }, [isActive, materials]);

//   return (
//     <group {...props} dispose={null}>
//       <group position={[-0.489, 1.057, -0.375]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube001.geometry}
//           material={blackMaterial}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube001_1.geometry}
//           material={latchesMaterial}
//         />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload('/models/parts144/kitchen-cabinet.glb');


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function KitchenCabinet(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/kitchen-cabinet.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.489, 1.057, -0.375]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials.latches}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/in-parts144/kitchen-cabinet.glb')