// import React, { useMemo, useState } from 'react';
// import { useGLTF, useTexture } from '@react-three/drei';
// import { useFrame } from '@react-three/fiber';

// export function KitchenWithSink({
//   isSelected,

//   waterLevel = 0.5, // 0-1 range
//   surfaceWear = 0.2, // 0-1 range
//   ...props
// }) {
//   const { nodes, materials } = useGLTF('./models/parts144/kitchen_withsink_onthecountertop.glb');


//   // Enhanced materials with wear effects
//   const counterMaterial = useMemo(() => {
//     const mat = materials.W_ma.clone();
//     mat.roughness = 0.1 + (0.3 * surfaceWear);
//     return mat;
//   }, [materials.W_ma, surfaceWear]);

//   const sinkMaterial = useMemo(() => {
//     const mat = materials['Material.031'].clone();
//     mat.metalness = 0.9;
//     mat.roughness = 0.05 + (0.2 * surfaceWear);
//     return mat;
//   }, [materials['Material.031'], surfaceWear]);

//   // Highlight materials
//   const highlightMaterial = useMemo(() => {
//     const mat = materials.W_ma.clone();
//     // material.emissive.set('blue');;
//     mat.emissiveIntensity = 0.5;
//     return mat;
//   }, [materials.W_ma]);



//   return (
//     <group {...props} dispose={null}>
//       <group position={[-0.559, 1.424, -0.491]}>
//         {/* Countertop */}
//         {nodes?.Cube015?.geometry && (
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube015.geometry}
//             material={isSelected ? highlightMaterial : counterMaterial}
//           />
//         )}

//         {/* Sink */}
//         {nodes?.Cube015_1?.geometry && (
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube015_1.geometry}
//             material={sinkMaterial}
//           />
//         )}
//       </group>


//     </group>
//   );
// }

// // useGLTF.preload('./models/parts144/kitchen_withsink_onthecountertop.glb');

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function KitchenWithSink(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/kitchen-withsink-onthecountertop.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.559, 1.424, -0.491]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={materials.W_ma}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_1.geometry}
          material={materials['Material.031']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/in-parts144/kitchen-withsink-onthecountertop.glb')