// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function OverTheCabStorageOne({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('/models/parts144/over-the-cab-storage-one.glb')

//   const storageMaterial = useMemo(() => {
//     const mat = materials['Material.033'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.7
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Plane029.geometry}
//         material={storageMaterial}
//         position={[-0.001, 2.158, 0.956]}
//       />
//     </group>
//   )
// }

// useGLTF.preload('/models/parts144/over-the-cab-storage-one.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function OverTheCabStorageOne(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/over-the-cab-storage-one.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane029.geometry}
        material={materials['Material.033']}
        position={[-0.001, 2.158, 0.956]}
      />
    </group>
  )
}

  useGLTF.preload('./models/in-parts144/over-the-cab-storage-one.glb')
