// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function OverTheCabStorageTwo({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('/models/parts144/over-the-cab-storage-two.glb')

//   const whiteMaterial = useMemo(() => {
//     const mat = materials.white.clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.6
//     }
//     return mat
//   }, [isActive, materials])

//   const material083 = useMemo(() => {
//     const mat = materials['Material.083'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.6
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <group position={[0.051, 2.147, 0.836]} scale={[2.507, 1.771, 1]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane002.geometry}
//           material={whiteMaterial}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane002_1.geometry}
//           material={material083}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/models/parts144/over-the-cab-storage-two.glb')


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function OverTheCabStorageTwo(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/over-the-cab-storage-two.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.051, 2.147, 0.836]} scale={[2.507, 1.771, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials.white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials['Material.083']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/in-parts144/over-the-cab-storage-two.glb')