// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function PartitionWallTwo(props) {
//   const { nodes, materials } = useGLTF('./models/parts144/partition-wall-two.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes['�����-�������7001'].geometry}
//         material={materials['Wood light']}
//         position={[-0.598, 1.48, -1.179]}
//       />
//     </group>
//   )
// }

// useGLTF.preload('./models/parts144/partition-wall-two.glb')


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function PartitionWallTwo(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/partition-wall-two.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['�����-�������7001'].geometry}
        material={materials['Wood light']}
        position={[-0.598, 1.48, -1.179]}
      />
    </group>
  )
}

  useGLTF.preload('./models/in-parts144/partition-wall-two.glb')
