// import React, { useMemo, useState } from 'react';
// import { useGLTF, useTexture } from '@react-three/drei';
// import { useFrame } from '@react-three/fiber';

// export function PopoutWindows({
//   isSelected,
//   isOpen = false,
//   tintColor = '#ffffff', // Default clear
//   tintOpacity = 0.3,
//   ...props
// }) {
//   const { nodes, materials } = useGLTF('./models/parts144/popouts.glb');
//   const [glassScratches] = useTexture(['/textures/glass-scratches-normal.jpg']);

//   // Glass material with configurable tint
//   const glassMaterial = useMemo(() => {
//     const material = materials['Material.001'].clone();
//     material.transparent = true;
//     material.opacity = tintOpacity;
//     material.color.set(tintColor);
//     material.normalMap = glassScratches;
//     material.normalScale.set(0.05, 0.05);
//     material.roughness = 0.1;
//     return material;
//   }, [materials['Material.001'], tintColor, tintOpacity]);

//   // Highlight material
//   const highlightMaterial = useMemo(() => {
//     const material = glassMaterial.clone();

//     material.emissiveIntensity = 0.3;
//     return material;
//   }, [glassMaterial]);

//   // Open/close animation
//   const [openProgress, setOpenProgress] = useState(0);
//   useFrame(() => {
//     setOpenProgress(prev => THREE.MathUtils.lerp(prev, isOpen ? 1 : 0, 0.1));
//   });

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube001.geometry}
//         material={isSelected ? highlightMaterial : glassMaterial}
//         position={[
//           -0.001,
//           1.811,
//           -1.776 + (openProgress * 0.2) // Slides out when open
//         ]}
//         rotation={[0, openProgress * 0.5, 0]} // Rotates open
//       >
//         {/* Optional inner frame when open */}
//         {openProgress > 0.1 && (
//           <mesh position={[0, 0, 0.1]}>
//             <boxGeometry args={[1.5, 1.2, 0.05]} />
//             <meshStandardMaterial
//               color="#333333"
//               metalness={0.5}
//               roughness={0.7}
//             />
//           </mesh>
//         )}
//       </mesh>
//     </group>
//   );
// }

// // useGLTF.preload('./models/parts144/popouts.glb');

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export  function PopoutWindows(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/popouts.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Material.001']}
        position={[-0.001, 1.811, -1.776]}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/popouts.glb')
