// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function ShowerBox({ isSelected, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/ShowerBox.glb');

//   const highlightedMaterial = useMemo(() => {
//     const material = materials.phong1.clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials.phong1]);

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Shower_box.geometry}
//         material={isSelected ? highlightedMaterial : materials.phong1}
//         position={[0.408, 0.824, -2.644]}
//       />
//     </group>
//   );
// }

// useGLTF.preload('./models/parts144/ShowerBox.glb');

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ShowerBox(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/shower-box.glb')
  return (
    <group {...props} dispose={null} position={[0.408, 0.724, -2.644]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shower_box.geometry}
        material={materials.phong1}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/shower-box.glb')
