// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function SinkCoverThree({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('/models/parts144/sink-cover-three.glb')

//   const coverMaterial = useMemo(() => {
//     const mat = materials['Material.037'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.6
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube013.geometry}
//         material={coverMaterial}
//         position={[-0.558, 1.499, -0.424]}
//         scale={[1.016, 1, 1.007]}
//       />
//     </group>
//   )
// }

// useGLTF.preload('/models/parts144/sink-cover-three.glb')


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SinkCoverThree(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/sink-cover-three.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials['Material.037']}
        position={[-0.558, 1.499, -0.424]}
        scale={[1.016, 1, 1.007]}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/sink-cover-three.glb')