// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function SinkCoverOne(props) {
//   const { nodes, materials } = useGLTF('./models/parts144/sink-cover-one.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube013.geometry}
//         material={materials['Material.037']}
//         position={[-0.558, 1.499, -0.424]}
//         scale={[1.016, 1, 1.007]}
//       />
//     </group>
//   )
// }

// useGLTF.preload('./models/parts144/sink-cover-one.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SinkCoverOne(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/sink-cover-one.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials['Material.037']}
        position={[-0.558, 1.499, -0.424]}
        scale={[1.016, 1, 1.007]}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/sink-cover-one.glb')