// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function SwivelSeat({ isVisible,isSelected, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/SwivelSeat.glb');

//   const highlightedMaterialBlack003 = useMemo(() => {
//     const material = materials['black.003'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['black.003']]);

//   const highlightedMaterial096 = useMemo(() => {
//     const material = materials['Material.096'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Material.096']]);

//   const highlightedMaterial006 = useMemo(() => {
//     const material = materials['Material.006'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Material.006']]);

//   const highlightedMaterialBlack014 = useMemo(() => {
//     const material = materials['black.014'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['black.014']]);

//   const highlightedMaterialRed008 = useMemo(() => {
//     const material = materials['red.008'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['red.008']]);

//   const highlightedMaterialBlack015 = useMemo(() => {
//     const material = materials['black.015'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['black.015']]);

//   const highlightedMaterialChrome010 = useMemo(() => {
//     const material = materials['chrome.010'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['chrome.010']]);

//   const highlightedMaterialChrome003 = useMemo(() => {
//     const material = materials['chrome.003'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['chrome.003']]);

//   return (
//     <group {...props} dispose={null} visible={isVisible}>
//       <group position={[0.429, 1.156, 0.18]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39014.geometry}
//           material={isSelected ? highlightedMaterialBlack003 : materials['black.003']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39014_1.geometry}
//           material={isSelected ? highlightedMaterial096 : materials['Material.096']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39014_2.geometry}
//           material={isSelected ? highlightedMaterial006 : materials['Material.006']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39014_3.geometry}
//           material={isSelected ? highlightedMaterialBlack014 : materials['black.014']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39014_4.geometry}
//           material={isSelected ? highlightedMaterialRed008 : materials['red.008']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39014_5.geometry}
//           material={isSelected ? highlightedMaterialBlack015 : materials['black.015']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39014_6.geometry}
//           material={isSelected ? highlightedMaterialChrome010 : materials['chrome.010']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.trunk_part_39014_7.geometry}
//           material={isSelected ? highlightedMaterialChrome003 : materials['chrome.003']}
//         />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload('./models/parts144/SwivelSeat.glb');


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SwivelSeat(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/swivel-seat.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.429, 1.156, 0.18]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39014.geometry}
          material={materials['black.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39014_1.geometry}
          material={materials['Material.096']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39014_2.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39014_3.geometry}
          material={materials['black.014']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39014_4.geometry}
          material={materials['red.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39014_5.geometry}
          material={materials['black.015']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39014_6.geometry}
          material={materials['chrome.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.trunk_part_39014_7.geometry}
          material={materials['chrome.003']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/in-parts144/swivel-seat.glb')