// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function SwivelTable({ isSelected, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/SwivelTable.glb');

//   const highlightedMaterial010 = useMemo(() => {
//     const material = materials['Material.010'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Material.010']]);

//   const highlightedMaterial011 = useMemo(() => {
//     const material = materials['Material.011'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Material.011']]);

//   const highlightedMaterial012 = useMemo(() => {
//     const material = materials['Material.012'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Material.012']]);

//   const highlightedMaterial013 = useMemo(() => {
//     const material = materials['Material.013'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Material.013']]);

//   const highlightedMaterial014 = useMemo(() => {
//     const material = materials['Material.014'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Material.014']]);

//   const highlightedMaterial015 = useMemo(() => {
//     const material = materials['Material.015'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Material.015']]);

//   return (
//     <group {...props} dispose={null}>
//       <group position={[-0.246, 0.695, -2.157]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube.geometry}
//           material={isSelected ? highlightedMaterial010 : materials['Material.010']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube_1.geometry}
//           material={isSelected ? highlightedMaterial011 : materials['Material.011']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube_2.geometry}
//           material={isSelected ? highlightedMaterial012 : materials['Material.012']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube_3.geometry}
//           material={isSelected ? highlightedMaterial013 : materials['Material.013']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube_4.geometry}
//           material={isSelected ? highlightedMaterial014 : materials['Material.014']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube_5.geometry}
//           material={isSelected ? highlightedMaterial015 : materials['Material.015']}
//         />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload('./models/parts144/SwivelTable.glb');

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SwivelTable(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/swivel-table.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.246, 0.695, -2.157]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials['Material.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials['Material.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials['Material.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_3.geometry}
          material={materials['Material.013']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_4.geometry}
          material={materials['Material.014']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_5.geometry}
          material={materials['Material.015']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/in-parts144/swivel-table.glb')