// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function TallCabinetFridge({ isSelected, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/TallCabinetFridge.glb');

//   const highlightedMaterial2 = useMemo(() => {
//     const material = materials.Material_2.clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials.Material_2]);

//   const highlightedMaterialLock002 = useMemo(() => {
//     const material = materials['lock.002'].clone();

//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['lock.002']]);

//   return (
//     <group {...props} dispose={null}>
//       <group position={[0.511, 1.547, -0.915]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_29_1.geometry}
//           material={isSelected ? highlightedMaterial2 : materials.Material_2}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_29_2.geometry}
//           material={isSelected ? highlightedMaterialLock002 : materials['lock.002']}
//         />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload('./models/parts144/TallCabinetFridge.glb');


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function TallCabinetFridge(props) {
//   const { nodes, materials } = useGLTF('./models/parts144/TallCabinetFridge.glb')
//   return (
//     <group {...props} dispose={null}>
//       <group position={[0.469, 1.818, -0.917]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube020.geometry}
//           material={materials['Brushed Aluminum']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube020_1.geometry}
//           material={materials['Brushed Steel Procedural.001']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube020_2.geometry}
//           material={materials['Material.020']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube020_3.geometry}
//           material={materials['Material.022']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube020_4.geometry}
//           material={materials['Material.023']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube020_5.geometry}
//           material={materials['Material.024']}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('./models/parts144/TallCabinetFridge.glb')
