// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export function UndermountSinkCover({ isSelected, ...props }) {
//   const { nodes, materials } = useGLTF('./models/parts144/undermount-sink-cover.glb');

//   // Highlight material for W_ma
//   const highlightedMaterial = useMemo(() => {
//     const material = materials.W_ma.clone();

//     material.emissiveIntensity = 1; // Slightly less intense for covers
//     return material;
//   }, [materials.W_ma]);

//   return (
//     <group {...props} dispose={null}>
//       {nodes?.Cube013?.geometry && (
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube013.geometry}
//           material={isSelected ? highlightedMaterial : materials.W_ma}
//           position={[-0.558, 1.505, -0.424]}
//           scale={[1.016, 1, 1.007]}
//         />
//       )}
//     </group>
//   );
// }

// useGLTF.preload('./models/parts144/undermount-sink-cover.glb');


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function UndermountSinkCover(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/undermount-sink-cover.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials.W_ma}
        position={[-0.558, 1.499, -0.424]}
        scale={[1.016, 1, 1.007]}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/undermount-sink-cover.glb')