// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function UpperCabinetFour(props) {
//   const { nodes, materials } = useGLTF('./models/parts144/upper-cabinet-four.glb')
//   return (
//     <group {...props} dispose={null}>
//       <group position={[-0.557, 2.304, -0.696]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-4_Антресоль_над_лавкой_Лораstl#2001_1'].geometry}
//           material={materials['LAXVIKEN noir']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-4_Антресоль_над_лавкой_Лораstl#2001_2'].geometry}
//           material={materials['Simple wood']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['C-4_Антресоль_над_лавкой_Лораstl#2001_3'].geometry}
//           material={materials.latches}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('./models/parts144/upper-cabinet-four.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function UpperCabinetFour(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/upper-cabinet-four.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.557, 2.304, -0.696]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-4_Антресоль_над_лавкой_Лораstl#2001_1'].geometry}
          material={materials['LAXVIKEN noir']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-4_Антресоль_над_лавкой_Лораstl#2001_2'].geometry}
          material={materials['Simple wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-4_Антресоль_над_лавкой_Лораstl#2001_3'].geometry}
          material={materials.latches}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/in-parts144/upper-cabinet-four.glb')