// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function UpperCabinetThree({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('/models/parts144/upper-cabinet-three.glb')

//   const woodMat = useMemo(() => {
//     const mat = materials['Simple wood'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.7
//     }
//     return mat
//   }, [isActive, materials])

//   const latchesMat = useMemo(() => {
//     const mat = materials.latches.clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.7
//     }
//     return mat
//   }, [isActive, materials])

//   const stepMat = useMemo(() => {
//     const mat = materials['STEP_ff00ff.001'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.7
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <group position={[-0.56, 2.304, -0.697]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Document007_1.geometry}
//           material={woodMat}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Document007_2.geometry}
//           material={latchesMat}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Document007_3.geometry}
//           material={stepMat}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/models/parts144/upper-cabinet-three.glb')


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function UpperCabinetThree(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/upper-cabinet-three.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.56, 2.304, -0.697]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Document007_1.geometry}
          material={materials['Simple wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Document007_2.geometry}
          material={materials.latches}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Document007_3.geometry}
          material={materials['STEP_ff00ff.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/in-parts144/upper-cabinet-three.glb')
