// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function UpperCabinetSix({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('/models/parts144/upper-cabinet-six.glb')

//   const wickerMat = useMemo(() => {
//     const mat = materials['Wicker texture var'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.7
//     }
//     return mat
//   }, [isActive, materials])

//   const material039 = useMemo(() => {
//     const mat = materials['Material.039'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.7
//     }
//     return mat
//   }, [isActive, materials])

//   const woodMat = useMemo(() => {
//     const mat = materials['Simple wood'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.7
//     }
//     return mat
//   }, [isActive, materials])

//   const latchesMat = useMemo(() => {
//     const mat = materials.latches.clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.7
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <group position={[-0.402, 2.326, -0.469]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane004.geometry}
//           material={wickerMat}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane004_1.geometry}
//           material={material039}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane004_2.geometry}
//           material={woodMat}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Plane004_3.geometry}
//           material={latchesMat}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/models/parts144/upper-cabinet-six.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function UpperCabinetSix(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/upper-cabinet-six.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.402, 2.326, -0.469]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={materials['Wicker texture var']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={materials['Material.039']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_2.geometry}
          material={materials['Simple wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_3.geometry}
          material={materials.latches}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/in-parts144/upper-cabinet-six.glb')
