// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function WallAndCeilingSix({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('/models/parts144/wall-and-ceiling-six.glb')

//   const woodMaterial = useMemo(() => {
//     const mat = materials['Wooden .003'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.6
//     }
//     return mat
//   }, [isActive, materials])

//   const blackMaterial = useMemo(() => {
//     const mat = materials['Bleck_S.003'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.6
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <group position={[-0.012, 2.492, -1.162]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh117.geometry}
//           material={woodMaterial}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh117_1.geometry}
//           material={blackMaterial}
//         />
//       </group>
//       <group position={[0.821, 1.332, 0.106]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh118.geometry}
//           material={woodMaterial}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh118_1.geometry}
//           material={blackMaterial}
//         />
//       </group>
//       <group position={[0.014, 1.673, -1.924]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh119.geometry}
//           material={woodMaterial}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh119_1.geometry}
//           material={blackMaterial}
//         />
//       </group>
//       <group position={[0.001, 1.51, -2.705]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh120.geometry}
//           material={woodMaterial}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Mesh120_1.geometry}
//           material={blackMaterial}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/models/parts144/wall-and-ceiling-six.glb')


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function WallAndCeilingSix(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/wall-and-ceiling-six.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.012, 2.492, -1.162]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh117.geometry}
          material={materials['Wooden .003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh117_1.geometry}
          material={materials['Bleck_S.003']}
        />
      </group>
      <group position={[0.821, 1.332, 0.106]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh118.geometry}
          material={materials['Wooden .003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh118_1.geometry}
          material={materials['Bleck_S.003']}
        />
      </group>
      <group position={[0.014, 1.673, -1.924]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh119.geometry}
          material={materials['Wooden .003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh119_1.geometry}
          material={materials['Bleck_S.003']}
        />
      </group>
      <group position={[0.001, 1.51, -2.705]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh120.geometry}
          material={materials['Wooden .003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh120_1.geometry}
          material={materials['Bleck_S.003']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/in-parts144/wall-and-ceiling-six.glb')