// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function WallAndCeilingFour({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('/models/parts144/wall-and-ceiling-four.glb')

//   const fabricMaterial = useMemo(() => {
//     const mat = materials['Grey furniture fabric.001'].clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.6
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Plane004.geometry}
//         material={fabricMaterial}
//         position={[-0.802, 1.669, -1.73]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Plane003.geometry}
//         material={fabricMaterial}
//         position={[0.809, 1.661, -1.676]}
//       />
//     </group>
//   )
// }

// useGLTF.preload('/models/parts144/wall-and-ceiling-four.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function WallAndCeilingFour(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/wall-and-ceiling-four.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials['Grey furniture fabric.001']}
        position={[-0.802, 1.669, -1.73]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials['Grey furniture fabric.001']}
        position={[0.809, 1.661, -1.676]}
      />
    </group>
  )
}

  useGLTF.preload('./models/in-parts144/wall-and-ceiling-four.glb')