// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function WallAndCeilingFive(props) {
//   const { nodes, materials } = useGLTF('./models/parts144/wall-and-ceiling-five.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes['<�������_�����_�___JJ>-<�_95c8aed'].geometry}
//         material={materials['Wood light']}
//         position={[0.167, 1.634, -1.443]}
//         rotation={[Math.PI / 2, 0, 0]}
//         scale={0.001}
//       />
//     </group>
//   )
// }

// useGLTF.preload('./models/parts144/wall-and-ceiling-five.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function WallAndCeilingFive(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/wall-and-ceiling-five.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['<�������_�����_�___JJ>-<�_95c8aed'].geometry}
        material={materials['Wood light']}
        position={[0.167, 1.634, -1.443]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.001}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/wall-and-ceiling-five.glb')