// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useMemo } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function WallAndCeilingOne({ isActive, ...props }) {
//   const { nodes, materials } = useGLTF('/models/parts144/wall-and-ceiling-one.glb')

//   const ceilingMaterial = useMemo(() => {
//     const mat = materials.ceiling.clone()
//     if (isActive) {
//       // material.emissive.set('blue');
//       mat.emissiveIntensity = 0.6
//     }
//     return mat
//   }, [isActive, materials])

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.EFI359.geometry}
//         material={ceilingMaterial}
//         position={[-0.04, 2.527, -1.096]}
//         rotation={[Math.PI / 2, 0, 0]}
//         scale={0.001}
//       />
//     </group>
//   )
// }

// useGLTF.preload('/models/parts144/wall-and-ceiling-one.glb')


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function WallAndCeilingOne(props) {
  const { nodes, materials } = useGLTF('./models/in-parts144/wall-and-ceiling-one.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.EFI359.geometry}
        material={materials.ceiling}
        position={[-0.04, 2.527, -1.096]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.001}
      />
    </group>
  )
}

useGLTF.preload('./models/in-parts144/wall-and-ceiling-one.glb')
