// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function BikeCarrier(props) {
//   const { nodes, materials } = useGLTF('./models/ex-parts144/carrier-with-bike.glb')

//   return (
//     <group {...props} dispose={null}>
//       <group
//         position={[-0.325, 1.996, -4.328]}
//         rotation={[Math.PI / 2, 0, -Math.PI / 2]}
//         scale={0.034}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.model_1_1.geometry}
//           material={materials['Material.047']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.model_1_2.geometry}
//           material={materials['Material.048']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.model_1_3.geometry}
//           material={materials['Material.038']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.model_1_4.geometry}
//           material={materials['Material.130']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.model_1_5.geometry}
//           material={materials['Material.043']}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('./models/ex-parts144/carrier-with-bike.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BikeCarrier(props) {
  const { nodes, materials } = useGLTF('./models/ex-parts144/carrier-with-bike.glb')
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.325, 1.996, -4.328]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.034}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.model_1_1.geometry}
          material={materials['Material.047']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.model_1_2.geometry}
          material={materials['Material.048']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.model_1_3.geometry}
          material={materials['Material.038']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.model_1_4.geometry}
          material={materials['Material.130']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.model_1_5.geometry}
          material={materials['Material.043']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/ex-parts144/carrier-with-bike.glb')