// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function HighRoofLadder({ isSelected, ...props }) {
//   const { nodes, materials } = useGLTF('./models/ex-parts144/HighRoofLadder.glb');

//   const highlightedMaterial008 = useMemo(() => {
//     const material = materials['Material.008'].clone();
//     // // material.emissive.set('red');
//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Material.008']]);

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube007.geometry}
//         material={isSelected ? highlightedMaterial008 : materials['Material.008']}
//         position={[0.915, 1.525, -0.986]}
//       />
//     </group>
//   );
// }

// useGLTF.preload('./models/ex-parts144/HighRoofLadder.glb');


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function HighRoofLadder(props) {
  const { nodes, materials } = useGLTF('./models/ex-parts144/HighRoofLadder.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials['Material.008']}
        position={[0.915, 1.525, -0.986]}
      />
    </group>
  )
}

useGLTF.preload('./models/ex-parts144/HighRoofLadder.glb')