// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function PopoutWindows({ isSelected, ...props }) {
//   const { nodes, materials } = useGLTF('./models/ex-parts144/PopoutWindows.glb');

//   const highlightedMaterial001 = useMemo(() => {
//     const material = materials['Material.001'].clone();
//     // // material.emissive.set('red');
//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Material.001']]);

//   const highlightedMaterial016 = useMemo(() => {
//     const material = materials['Material.016'].clone();
//     // // material.emissive.set('red');
//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Material.016']]);

//   return (
//     <group {...props} dispose={null}>
//       <group position={[1.041, 1.868, -1.873]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube002.geometry}
//           material={isSelected ? highlightedMaterial001 : materials['Material.001']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube002_1.geometry}
//           material={isSelected ? highlightedMaterial016 : materials['Material.016']}
//         />
//       </group>
//       <group position={[-1.043, 1.861, -1.855]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube009_1.geometry}
//           material={isSelected ? highlightedMaterial001 : materials['Material.001']}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube009_2.geometry}
//           material={isSelected ? highlightedMaterial016 : materials['Material.016']}
//         />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload('./models/ex-parts144/PopoutWindows.glb');

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function PopoutWindows(props) {
  const { nodes, materials } = useGLTF('./models/ex-parts144/popout-windows.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.041, 1.868, -1.873]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials['Material.016']}
        />
      </group>
      <group position={[-1.043, 1.861, -1.855]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_2.geometry}
          material={materials['Material.016']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/ex-parts144/popout-windows.glb')