import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function RearStorageBox(props) {
  const { nodes, materials } = useGLTF('./models/ex-parts144/rear-storage-box-one.glb')

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046.geometry}
        material={materials['Material.019']}
        position={[0.584, 1.147, -3.306]}
      />
    </group>
  )
}

useGLTF.preload('./models/ex-parts144/rear-storage-box-one.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

