// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function RoofRack({ isSelected, ...props }) {
//   const { nodes, materials } = useGLTF('./models/ex-parts144/RoofRack.glb');

//   const highlightedMaterial009 = useMemo(() => {
//     const material = materials['Material.009'].clone();
//     // // material.emissive.set('red');
//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Material.009']]);

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube023.geometry}
//         material={isSelected ? highlightedMaterial009 : materials['Material.009']}
//         position={[0.04, 2.637, -0.93]}
//       />
//     </group>
//   );
// }

// useGLTF.preload('./models/ex-parts144/RoofRack.glb');

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function RoofRack(props) {
  const { nodes, materials } = useGLTF('./models/ex-parts144/RoofRack.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials['Material.009']}
        position={[0.04, 2.637, -0.93]}
      />
    </group>
  )
}

useGLTF.preload('./models/ex-parts144/RoofRack.glb')
