// import React, { useMemo } from 'react';
// import { useGLTF } from '@react-three/drei';

// export default function Solar({ isSelected, ...props }) {
//   const { nodes, materials } = useGLTF('./models/ex-parts144/Solar.glb');

//   const highlightedMaterialSolar = useMemo(() => {
//     const material = materials['Ekran Resmi 2020-07-10 11.50.07 kopyası'].clone();
//     // // material.emissive.set('red');
//     material.emissiveIntensity = 1;
//     return material;
//   }, [materials['Ekran Resmi 2020-07-10 11.50.07 kopyası']]);

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.SP.geometry}
//         material={isSelected ? highlightedMaterialSolar : materials['Ekran Resmi 2020-07-10 11.50.07 kopyası']}
//         position={[-0.406, 2.673, -1.853]}
//         rotation={[Math.PI / 2, 0, 0]}
//         scale={0.01}
//       />
//     </group>
//   );
// }

// useGLTF.preload('./models/ex-parts144/Solar.glb');

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Solar(props) {
  const { nodes, materials } = useGLTF('./models/ex-parts144/Solar.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SP.geometry}
        material={materials['Ekran Resmi 2020-07-10 11.50.07 kopyası']}
        position={[-0.406, 2.673, -1.853]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  )
}

useGLTF.preload('./models/ex-parts144/Solar.glb')