export const MAX_QUANTITY = {
    Ceiling: 1,
    "Control Panel": 1,
    "Dinette Bed": 1,
    "Dinette Cushion Set": 1,
    "Elevator Bed": 1,
    "Jump Seat": 1,
    Kitchen: 1,
    "Maxx Air Fan": 1,
    Microwave: 1,
    "Popout Windows Acrylic": 2,
    "Reading Light": 3,
    Shower: 1,
    "Shower Box": 1,
    "Storage Box": 2,
    "Swivel Seat": 1,
    "Swivel Table": 1,
    "Tall Cabinet Fridge": 1,
    "Tall Cabinet Hanger": 1,
    "Tall Fridge": 1,
    "Wall Cabinet Above Kitchen": 1,
    "Wall Cabinet Behind Driver": 1,
    "Wall Cabinet Driver Side": 1,
    "Wall Panel": 1,
    Ac: 1,
    Awning: 2,
    "Back Carrier": 1,
    "High Roof Ladder": 1,
    "Popout Windows": 2,
    "Roof Rack": 1,
    Solar: 2,
  };

